// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGwXPPZCilXPJIDRoo8wpBKwfwBqtP04',
    appId: '1:841286673346:web:2da61b3803b8e8b473ec5b',
    messagingSenderId: '841286673346',
    projectId: 'ecommerce-70953',
    authDomain: 'ecommerce-70953.firebaseapp.com',
    storageBucket: 'ecommerce-70953.firebasestorage.app',
    measurementId: 'G-VHMTX071KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIuYALgJLPdRu8c_QflaVTW8tLaXW4XdE',
    appId: '1:841286673346:android:7cf52f1bb5c47f3d73ec5b',
    messagingSenderId: '841286673346',
    projectId: 'ecommerce-70953',
    storageBucket: 'ecommerce-70953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7zCeihR-F9rcHPeVrngUY8aKZJvEUb4A',
    appId: '1:841286673346:ios:ec5e508293533b3a73ec5b',
    messagingSenderId: '841286673346',
    projectId: 'ecommerce-70953',
    storageBucket: 'ecommerce-70953.firebasestorage.app',
    iosClientId: '841286673346-q2p7r0l950dsr4u0h2dof43p4g9p3sev.apps.googleusercontent.com',
    iosBundleId: 'com.example.lazashopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7zCeihR-F9rcHPeVrngUY8aKZJvEUb4A',
    appId: '1:841286673346:ios:ec5e508293533b3a73ec5b',
    messagingSenderId: '841286673346',
    projectId: 'ecommerce-70953',
    storageBucket: 'ecommerce-70953.firebasestorage.app',
    iosClientId: '841286673346-q2p7r0l950dsr4u0h2dof43p4g9p3sev.apps.googleusercontent.com',
    iosBundleId: 'com.example.lazashopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJGwXPPZCilXPJIDRoo8wpBKwfwBqtP04',
    appId: '1:841286673346:web:1ea432c63462a6fa73ec5b',
    messagingSenderId: '841286673346',
    projectId: 'ecommerce-70953',
    authDomain: 'ecommerce-70953.firebaseapp.com',
    storageBucket: 'ecommerce-70953.firebasestorage.app',
    measurementId: 'G-BTSF64J3V5',
  );
}
